dirs:
  root: .
  css: css
  sass: sass
  images: images
  scripts: js
  fonts: fonts
  export: export

compass:
  dependencies:
    sass: '~>3.2.0'
    toolkit: '<2.0.0'
    compass-normalize: "<2.0.0"
    compass: '~>0.13.alpha.4'
    rb-fsevent: "~>0.9"
    singularity-extras: "<1.0.0"
    jacket: "~>1.0.0"
  import_paths:
    - bower_components/eq.js/sass
  relative_assets: true

server:
  port: 9001
  livereload: 9002